=== Deltares-research/DHYDROGUI/src/DeltaShell.Dimr/xsd/dimr-1.0.xsd
<?xml version="1.0" encoding="utf-8"?>

<!-- edited with XMLSpy v2014 rel. 2 sp1 (http://www.altova.com) by Afdeling ICT (Stichting Deltares) -->
<!--W3C Schema generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<xs:schema xmlns:dimr="http://schemas.deltares.nl/dimr" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.deltares.nl/dimr" elementFormDefault="qualified">
  <xs:complexType name="dimrDocumentationXML">
    <xs:annotation>
      <xs:documentation>information on the present DIMR configuration file</xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="fileVersion">
        <xs:annotation>
          <xs:documentation>DIMR configuration file version</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:enumeration value="1.0" />
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="creationDate" type="xs:dateTime" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Date/time when the file was created/edited</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="createdBy" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Tool that created the file</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="dimrControlXML">
    <xs:annotation>
      <xs:documentation>Control flow specification for the DIMR-execution. Executed sequentially, except for components in a "parallel" element</xs:documentation>
    </xs:annotation>
    <xs:choice maxOccurs="unbounded">
      <xs:element name="parallel" type="dimr:dimrParallelXML">
        <xs:annotation>
          <xs:documentation>Specification of a control flow that has to be executed in parallel</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="start" type="dimr:dimrComponentOrCouplerRefXML">
        <xs:annotation>
          <xs:documentation>Reference to the component instance to be started</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="dimrParallelXML">
    <xs:annotation>
      <xs:documentation>Specification of a parallel control flow (one main component and a group of related components and couplers). Step wise execution order according to order in parallel control flow.</xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:sequence>
        <xs:element name="startGroup" type="dimr:dimrStartGroupXML">
          <xs:annotation>
            <xs:documentation>Group of components and couplers to be executed according to the frequency in the "time" element</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="start" type="dimr:dimrComponentOrCouplerRefXML">
          <xs:annotation>
            <xs:documentation>Main component to be executed step wise (provides start time, end time and time step)</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
      <xs:sequence>
        <xs:element name="start" type="dimr:dimrComponentOrCouplerRefXML">
          <xs:annotation>
            <xs:documentation>Main component to be executed step wise (provides start time, end time and time step)</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="startGroup" type="dimr:dimrStartGroupXML">
          <xs:annotation>
            <xs:documentation>Group of components and couplers to be executed according to the frequency in the "time" element</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="dimrStartGroupXML">
    <xs:annotation>
      <xs:documentation>Specification of model components and couplers to be executed with a certain frequency</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="time" type="xs:string">
        <xs:annotation>
          <xs:documentation>Time frame specification for the present group (start and stop time and frequency, expressed in terms of the time frame of the main component)</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:choice maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Ordered list of components and/or couplers (specifies the execution order) </xs:documentation>
        </xs:annotation>
        <xs:element name="start" type="dimr:dimrComponentOrCouplerRefXML">
          <xs:annotation>
            <xs:documentation>Reference to a component to be executed</xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element name="coupler" type="dimr:dimrComponentOrCouplerRefXML">
          <xs:annotation>
            <xs:documentation>Reference to a coupler to be executed</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dimrSequentialXML">
    <xs:annotation>
      <xs:documentation>Specification of a sequential control flow (components and couplers)</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="start" type="dimr:dimrComponentOrCouplerRefXML" />
      <!-- TODO: sequence of components and couplers? -->
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dimrComponentOrCouplerRefXML">
    <xs:annotation>
      <xs:documentation>Reference to a BMI-compliant model component instance specified below</xs:documentation>
    </xs:annotation>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>
  <xs:complexType name="dimrComponentXML">
    <xs:annotation>
      <xs:documentation>Specification of a BMI-compliant model component instance that will be executed by DIMR</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="library" type="xs:string">
        <xs:annotation>
          <xs:documentation>DLL/so that contains the implementation of the model component instance</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="process" type="xs:integer" default="0" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Number of subprocesses in the model component instance (0 if there is no parallel computation)</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="workingDir" type="xs:string">
        <xs:annotation>
          <xs:documentation>Working directory for the model component instance</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="inputFile" type="xs:string">
        <xs:annotation>
          <xs:documentation>Main input file (configuration file) for the model component instance</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The component's identifying name (unique within the present DIMR config)</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="dimrCouplerXML">
    <xs:annotation>
      <xs:documentation>Specification of the coupling actions to be performed between two BMI-compliant model components</xs:documentation>
    </xs:annotation>
    <xs:sequence minOccurs="0">
      <xs:element name="sourceComponent" type="xs:string">
        <xs:annotation>
          <xs:documentation>The component that provides the data to has to be exchanged</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="targetComponent" type="xs:string">
        <xs:annotation>
          <xs:documentation>The component that consumes the data to has to be exchanged</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="item" type="dimr:dimrCoupledItemXML" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>One or more items that have to be exchanged</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>The coupler's identifying name (unique within the present DIMR config)</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="dimrCoupledItemXML">
    <xs:annotation>
      <xs:documentation>Specification of an item that has to be exchanged</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="sourceName" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of the item at source component side</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="targetName" type="xs:string">
        <xs:annotation>
          <xs:documentation>Name of the item at target component side</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="dimrXML">
    <xs:annotation>
      <xs:documentation>Specification of a configuration that can be executed by DIMR</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="documentation" type="dimr:dimrDocumentationXML">
        <xs:annotation>
          <xs:documentation>Information about this DIMR configuration</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="waitFile" type="xs:string" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Optional: file path to wait for before the initialization process starts (useful for attaching to process when debugging)</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="control" type="dimr:dimrControlXML">
        <xs:annotation>
          <xs:documentation>Control flow specification</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="component" type="dimr:dimrComponentXML" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Involved components</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="coupler" type="dimr:dimrCouplerXML" minOccurs="0" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>Involved couplers</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="dimrConfig" type="dimr:dimrXML">
    <xs:annotation>
      <xs:documentation>Configuration file for DIMR</xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>

=== Deltares-research/DHYDROGUI/test/DeltaShell.Plugins.FMSuite.FlowFM.Tests/test-data/DSCTestBenchTests/f100_1D/c04_closed_channel_circle/dimr_config.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<dimrConfig xmlns="http://schemas.deltares.nl/dimr" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.deltares.nl/dimr http://content.oss.deltares.nl/schemas/dimr-1.0.xsd">
    <documentation>
        <fileVersion>1.00</fileVersion>
        <createdBy>Deltares, dflowfm_to_dimr_xml.py</createdBy>
        <creationDate>2017-06-15T15:03:55.212000Z</creationDate>
    </documentation>
    <control>
        <start name="DFlowFM"/>
    </control>
    <component name="DFlowFM">
        <library>dflowfm</library>
        <process>0</process>
        <workingDir>.</workingDir>
        <inputFile>FlowFM.mdu</inputFile>
    </component>
</dimrConfig>

=== Deltares-research/DHYDROGUI/test/DeltaShell.Plugins.FMSuite.FlowFM.Tests/test-data/LegacyLoaderOutput/run_with_save_and_custom_output/TestProject.dsproj_data/TestModel_output/dimr.xml
<?xml version="1.0"?>
<dimrConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.deltares.nl/dimr http://content.oss.deltares.nl/schemas/dimr-1.0.xsd" xmlns="http://schemas.deltares.nl/dimr">
  <documentation>
    <fileVersion>1</fileVersion>
    <createdBy>Deltares, Coupling Team</createdBy>
  </documentation>
  <control>
    <start name="TestModel" />
  </control>
  <component name="TestModel">
    <library>dflowfm</library>
    <workingDir>dflowfm</workingDir>
    <inputFile>TestModel.mdu</inputFile>
  </component>
</dimrConfig>
