=== Deltares-research/DHYDROGUI/src/DeltaShell.Plugins.DelftModels.RealTimeControl/Xsd/treeVector.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:openda="http://www.openda.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.openda.org" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- File containing a TreeVector -->
	<xs:element name="treeVectorFile" type="openda:TreeVectorFileXML">
		<xs:annotation>
			<xs:documentation>Costa / DATools Tree Vector File</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="TreeVectorFileXML">
		<xs:sequence>
			<xs:element name="timeStamp" type="openda:DateTimeXML" minOccurs="0"/>
			<xs:element name="treeVector" type="openda:TreeVectorXML"/>
		</xs:sequence>
	</xs:complexType>
	<!-- TreeVector -->
	<xs:complexType name="TreeVectorXML">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="treeVectorLeaf" type="openda:TreeVectorLeafXML"/>
				<xs:element name="subTreeVector" type="openda:TreeVectorXML"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="caption" type="xs:string"/>
		<xs:attribute name="excludeFromVector" type="xs:boolean" use="optional"/>
		<xs:attribute name="className" type="xs:string"/>
	</xs:complexType>
	<!-- Known leaf types -->
	<!-- Vector -->
	<xs:complexType name="TreeVectorLeafXML">
		<xs:sequence>
			<xs:element name="unit" type="xs:string" minOccurs="0"/>
			<xs:element name="missingValue" type="xs:double" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="dimensions" type="openda:DimensionsXML"/>
				<xs:element name="grid" type="openda:GridXML"/>
			</xs:choice>
			<xs:element name="vector" type="openda:VectorXML"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
		<xs:attribute name="caption" type="xs:string"/>
		<xs:attribute name="excludeFromVector" type="xs:boolean" use="optional"/>
		<xs:attribute name="className" type="xs:string"/>
	</xs:complexType>
	<!-- nD-dimension type (to be elaborated)  -->
	<xs:complexType name="DimensionsXML">
		<xs:attribute name="dimSize1" type="xs:string" use="required"/>
		<xs:attribute name="dimSize2" type="xs:string" use="optional"/>
		<xs:attribute name="dimSize3" type="xs:string" use="optional"/>
	</xs:complexType>
	<!-- Grid and Computational/Physical dimension types -->
	<xs:complexType name="GridXML">
		<xs:sequence>
			<xs:element name="computationalSpace" type="openda:ComputationalSpaceXML"/>
			<xs:element name="physicalSpace" type="openda:PhysicalSpaceXML" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ComputationalSpaceXML">
		<xs:sequence>
			<xs:element name="dimension" type="openda:ComputationalDimensionXML" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ComputationalDimensionXML">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="length" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="PhysicalSpaceXML">
		<xs:sequence>
			<xs:element name="dimension" type="openda:PhysicalDimensionXML" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PhysicalDimensionXML">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="axes" type="xs:string" use="required"/>
		<xs:attribute name="ref" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="MetaInfoXML">
		<xs:sequence/>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	<!-- Date / Time types -->
	<xs:complexType name="DateTimeXML">
		<xs:attribute name="date" type="openda:DateXML" use="required">
			<xs:annotation>
				<xs:documentation>ISO 8601 (yyyy-mm-dd)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="time" type="openda:TimeXML" use="required">
			<xs:annotation>
				<xs:documentation>ISO 8601 (hh:mm:ss[.msec])</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="timeZone" type="openda:TimeZoneXML" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="DateXML">
		<xs:restriction base="xs:date">
			<xs:pattern value="\d\d\d\d-\d\d-\d\d"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimeXML">
		<xs:restriction base="xs:time">
			<xs:pattern value="\d\d:\d\d:\d\d"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Values types -->
	<xs:simpleType name="VectorXML">
		<xs:restriction base="xs:string">
			<!-- (stack overflow:) <xs:pattern value="[ \n\t]*[\-+0-9.eENa]+([ \n\t]+[\-+0-9.eENa]+)*[ \n\t]*"/> -->
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TimeZoneXML">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z][A-Z][A-Z][A-Z]?"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Deltares-research/DHYDROGUI/test/DeltaShell.NGHS.IO.Tests/test-data/FileReaders/ConfigXmlReader/RtcXmlFiles/state_import.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<treeVectorFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openda.org" xsi:schemaLocation="http://www.openda.org D:\sluis_pa\Documents\WORK\Export%20files\rtc\treeVector.xsd">
  <treeVector>
    <treeVectorLeaf id="[Output]Maeslant_drempel/Crest width (s)">
      <vector>360</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Maeslant_schuif/Crest width (s)">
      <vector>360</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Maeslant_schuif/Gate lower edge level (s)">
      <vector>-17</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Maeslant_over/Crest level (s)">
      <vector>2</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Maeslant_over/Crest width (s)">
      <vector>0</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Hartel_breed/Gate lower edge level (s)">
      <vector>13.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Hartel_smal/Gate lower edge level (s)">
      <vector>13.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Hartel_breed_ovl/Crest level (s)">
      <vector>23</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Hartel_smal_ovl/Crest level (s)">
      <vector>23</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]HolIJsselkering/Gate lower edge level (s)">
      <vector>12.100000000000001</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Volkerak_over/Crest level (s)">
      <vector>3.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Volkerak_schuiven/Gate lower edge level (s)">
      <vector>-4.25</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet1/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet2/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet3/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet4/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet5/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet6/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet7/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet8/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet9/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet10/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet11/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet12/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet13/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet14/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet15/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet16/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Haringvliet17/Gate lower edge level (s)">
      <vector>-5.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Kromme Nolkering/Gate lower edge level (s)">
      <vector>11.1</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]zwd_BathseSpuisl/Gate lower edge level (s)">
      <vector>-4.25</vector>
    </treeVectorLeaf>
  </treeVector>
</treeVectorFile>

=== Deltares-research/DHYDROGUI/1d2d/test/DeltaShell.Plugins.DelftModels.HydroModel.Tests/test-data/SimpleModel/rtc/state_import.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<treeVectorFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openda.org" xsi:schemaLocation="http://www.openda.org C:\D-HYDRO-test\_SimpleModel\export\rtc\treeVector.xsd">
  <treeVector>
    <treeVectorLeaf id="[Output]NW_1026.34_C_SK_Maeslantkering/GateOpeningWidth">
      <vector>NaN</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]NW_1026.34_C_SK_Maeslantkering/GateLowerEdgeLevel">
      <vector>NaN</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]HK_1.67_C_SK_HartelkeringZ/GateLowerEdgeLevel">
      <vector>NaN</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]HK_1.67_R_SK_HartelkeringN/GateLowerEdgeLevel">
      <vector>NaN</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]HD_998.75_L_US_Volkeraksluizen/GateLowerEdgeLevel">
      <vector>NaN</vector>
    </treeVectorLeaf>
  </treeVector>
</treeVectorFile>

=== Deltares-research/DHYDROGUI/test/DeltaShell.Plugins.DelftModels.HydroModel.Tests/test-data/HydroModelConverterTest/rtc/state_export.xml
<?xml version="1.0" encoding="UTF-8"?>
<treeVectorFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openda.org" xsi:schemaLocation="http://www.openda.org ../../../xsd/treeVector.xsd">
  <treeVector>
    <treeVectorLeaf id="[Input]ObservationPoint01/water_level">
      <vector>0  0 0 </vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="Control Group 1/rule01">
      <vector>0  0 0 </vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="Control Group 2/rule01">
      <vector>0  0 0 </vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]structure01/CrestLevel">
      <vector>NaN  NaN NaN </vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Status]Control Group 1/condition01">
      <vector>1  1 1 </vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]structure02/CrestLevel">
      <vector>NaN  NaN NaN </vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Status]Control Group 2/condition01">
      <vector>1  1 1 </vector>
    </treeVectorLeaf>
  </treeVector>
</treeVectorFile>

=== Deltares-research/DHYDROGUI/test/DeltaShell.NGHS.IO.Tests/test-data/FileReaders/ConfigXmlReader/rtc/state_import.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<treeVectorFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openda.org" xsi:schemaLocation="http://www.openda.org C:\Users\veen_jn\Desktop\AcceptanceModels\c01_sobek-rijn-j17_5-v1\sobek-rijn-j17_5-v1\dimr_expected\rtc\treeVector.xsd">
  <treeVector>
    <treeVectorLeaf id="output_ST_Driel_zom_Crest level (s)">
      <vector>1.7</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_ST_Driel_zom_Crest width (s)">
      <vector>96</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_ST_Amerongen_zom_Crest level (s)">
      <vector>-2</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_ST_Amerongen_zom_Crest width (s)">
      <vector>96</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_ST_Hagestein_zom_Crest level (s)">
      <vector>-4.55</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_ST_Hagestein_zom_Crest width (s)">
      <vector>96</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_Sluis_Marijke_Gate lower edge level (s)">
      <vector>-2</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_Sluis_Bernhard_Gate lower edge level (s)">
      <vector>-2</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_ST_Driel_oml_Crest level (s)">
      <vector>3.2</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_ST_Amerongen_oml_Crest level (s)">
      <vector>-1</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_ST_Hagestein_oml_Crest level (s)">
      <vector>-3.5</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_Blok1_Vees_wap_Crest level (s)">
      <vector>5.65</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_VeesWap1_onttrek_Actual discharge (l)">
      <vector>-100</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_Blok2_Vees_wap_Crest level (s)">
      <vector>5.65</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_Blok3_Vees_wap_Crest level (s)">
      <vector>5.65</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="output_Blok4_Vees_wap_Crest level (s)">
      <vector>5.65</vector>
    </treeVectorLeaf>
  </treeVector>
</treeVectorFile>

=== Deltares-research/DHYDROGUI/test/DeltaShell.Plugins.FMSuite.FlowFM.Tests/test-data/c071_generalstructure_door_closing_at_sill/rtc/state_import.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<treeVectorFile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openda.org" xsi:schemaLocation="http://www.openda.org F:\checkouts\svn\DSCTestbench\trunk\cases\e105_dflowfm-drtc\f01_general\c072_generalstructure_lowering_open_door\e105-f01-c072.dsproj_data\Integrated_Model_output\rtc\treeVector.xsd">
  <treeVector>
    <treeVectorLeaf id="[Output]Maeslantkering/GateLowerEdgeLevel">
      <vector>NaN</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Maeslantkering/GateOpeningWidth">
      <vector>NaN</vector>
    </treeVectorLeaf>
    <treeVectorLeaf id="[Output]Maeslantkering/CrestLevel">
      <vector>NaN</vector>
    </treeVectorLeaf>
  </treeVector>
</treeVectorFile>
